name: SmartPick CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: smartpick
          POSTGRES_PASSWORD: smartpick
          POSTGRES_DB: smartpick
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Backend deps and build
        working-directory: backend
        run: |
          npm install
          npm run build

      - name: Frontend deps
        working-directory: frontend
        run: |
          npm install
          npm run build || echo "skip build for placeholder"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Vision service deps and tests
        working-directory: vision-service
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pytest -q || echo "skip tests for placeholder"
